language: node_js

node_js:
  - lts/*

cache: yarn

script:
  - yarn lint

before_deploy:
  - yarn build

deploy:
  provider: releases
  api_key:
    secure: DR/cLu8NLKCUUiBBrWplCpyeDv89tsR/AJu/Um22HwouRV6Euuj62ovaaZyMA/8HE1i0NtRGJTblWeJN/uAlpXtdloAqSZU1zyc84R/bs10fMquiKVKFktEvXjz1HdajwbMjCyiXJO6vIDBuzUXfwBUIa0eXC70qqDeZEMAjNV/wOexqbrb7ZuvvWwrDxb8APxdIe8nhVkmfcJ9CQ0fUdDv18tPgsT8txhaaJCWLpFAJQqR7e0LlQN/vXhcJkWJxFk77ZspbML7iHk/YhKCfu67kjvmKTXAU6F0xt4Fyh9G6ya9lpiz5CFkaJvn3P1bHCpdsX6jnB112bQNAN4eo2APUjn9HSf0nG4Nz4w02xC7RoZQJiFT0GfODjiCU3DGHUgtU5+LB//Bl7rXNdGxFRVaQ3Zv36AbgxAb+ZaPEf6UfamODaxKboBw5XBdkI4/AlV4O3fB48mCJI165YVBEoA7DzRjUg0nZWC5hQldRk8gZjQg8K0RPr+TZhYOjV9zeRsxcveTDV7WWWU8AuiGwNKWuY7eCKyJKukcu1y9DGy9ZcFaEnSfLoDJNtqFtiht92f+U9RrjfcCT30CvB3xvT5tnf3bVFYKwvuF7XCgLUutS8jdqKF+Qjd571jhEnU8MBXIA+7OzrGwnSRQbG+hd372hizuWcpDbI/O1/DCoweU=
  file: dist/battlecode.d.ts
  on:
    tags: true
